site_name: SbatchMan
site_url: !ENV READTHEDOCS_CANONICAL_URL
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.top
    - navigation.instant
    - content.code.copy
    - search.suggest
    - header.autohide
  palette:
    - scheme: default
      primary: black   # ⬅️ Black top bar (in light mode)
      accent: dark blue
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: black   # ⬅️ Black top bar (in dark mode)
      accent: dark blue
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.tabbed
  - pymdownx.emoji

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          inventories:
          - https://docs.python.org/3/objects.inv
          options:
            separate_signature: true
            show_signature_annotations: true
            signature_crossrefs: true
            show_symbol_type_heading: true
            group_by_category: true
            show_symbol_type_toc: true
            show_source: false
            show_if_no_docstring: true
            merge_init_into_class: true
nav:
  - Home: index.md
  - Learn:
    - Installation: learn/install.md
    - Tutorial: learn/tutorial.md
    - Advanced configuration: learn/configuration.md
    - Advanced job submission: learn/launching_jobs.md
    - Aliases: learn/aliases.md
  - API: api.md
