site_name: SbatchMan
site_url: https://example.com/
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.instant
    - search.suggest
    - content.code.annotate
    - toc.integrate
  palette:
    - scheme: default
      primary: indigo
      accent: pink

nav:
  - Home: index.md
  - Installation: install.md
  - Learn: learn.md
  - API: api.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google